package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/MXLange/desafio-pos-clean-architecture/internal/domain/order/dto"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input dto.OrderCreateRequest) (*dto.Order, error) {
	res, err := r.CreateOrderUseCase.Execute(ctx, &input)
	if err != nil {
		return nil, err
	}

	return &dto.Order{
		ID:        res.ID,
		ProductID: res.ProductID,
		Quantity:  res.Quantity,
	}, nil
}

// ID is the resolver for the id field.
func (r *orderResolver) ID(ctx context.Context, obj *dto.Order) (int32, error) {
	return int32(obj.ID), nil
}

// ProductID is the resolver for the productId field.
func (r *orderResolver) ProductID(ctx context.Context, obj *dto.Order) (int32, error) {
	return int32(obj.ProductID), nil
}

// Quantity is the resolver for the quantity field.
func (r *orderResolver) Quantity(ctx context.Context, obj *dto.Order) (int32, error) {
	return int32(obj.Quantity), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*dto.Order, error) {
	orders, err := r.ListOrdersUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*dto.Order, 0, len(orders))
	for _, order := range orders {
		res = append(res, &order)
	}

	return res, nil
}

// ProductID is the resolver for the productId field.
func (r *newOrderResolver) ProductID(ctx context.Context, obj *dto.OrderCreateRequest, data int32) error {
	obj.ProductID = uint(data)
	return nil
}

// Quantity is the resolver for the quantity field.
func (r *newOrderResolver) Quantity(ctx context.Context, obj *dto.OrderCreateRequest, data int32) error {
	obj.Quantity = uint(data)
	return nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// NewOrder returns NewOrderResolver implementation.
func (r *Resolver) NewOrder() NewOrderResolver { return &newOrderResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type newOrderResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
